# Generated by Django 5.1.3 on 2024-12-11 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_historicoclientes_registroclientes'),
        ('estetica', '0002_agenda_created_at_agenda_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to='clientes.registroclientes'),
        ),
        migrations.AlterField(
            model_name='historicoprocedimentos',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_procedimentos', to='clientes.registroclientes'),
        ),
        migrations.AlterField(
            model_name='registroatendimento',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atendimentos', to='clientes.registroclientes'),
        ),
    ]
