# Generated by Django 5.1.3 on 2024-12-11 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_historicoclientes_registroclientes'),
        ('estetica', '0003_alter_agenda_cliente_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Clientes',
        ),
        migrations.AddField(
            model_name='historicoclientes',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='clientes.registroclientes'),
        ),
    ]
